### ISSUE TITLE
Going to new tab in same window breaks current track

### ISSUE THREAD

**Issue by mparker11** [ToneDen/toneden-sdk#20]
I believe this is an issue, but may need to be tested more. A few times I had the player playing and after a minute of being in another tab, the player froze and made a "frozen" high-pitched noise. The only way to stop it was to close the tab and visit my website again. It seems to work ok if I have the website open in a window and browse other sites on a second window, but never the same window.

Browser: Chrome 35.0.1916.114 - latest as of today
Computer Specs: 3 monitors, 2 processors (6 cores each) - 2.3 GHz, 32 GB RAM
* I have quite a bit running on my machine but I don't believe that's the problem...giving you specs just to make sure.

**Comment by jackrugile** [comment]
+1 to this, on Chrome Version 40.0.2214.115 (64-bit)

**Comment by elsbree** [comment]
V2 was just released- this issue should no longer be present. You will have to change your embed code, since v2 incorporates some breaking changes to the API.
