### ISSUE TITLE
Changing Views in AngularJS hides ToneDen

### ISSUE THREAD

**Issue by LeedleDev** [ToneDen/toneden-sdk#33]
I am running an AngularJS application and I have my script loaded in one of my views. If you leave that view and come back the interface will disappear but the sound will keep playing.

**Comment by LeedleDev** [comment]
Fixed using this workaround: https://github.com/ToneDen/toneden-sdk/issues/13

I would HIGHLY recommend writing an angular module to support angular with more ease eventually.

Thanks for the awesome player!

**Comment by elsbree** [comment]
Glad you were able to find a fix! I was going to recommend calling the `destroy()` method on the player instance before changing views to ensure that the player is getting properly removed from the page.

I'd love to write an Angular module for the player, but first I'd have to learn Angular... I'm using React/Flux at the moment at ToneDen, so I'd probably write a React component for the player before an Angular module. Feel free to take a crack at it though ;)
