### ISSUE TITLE
Streaming url ids, not http links

### ISSUE THREAD

**Issue by gvossos** [ToneDen/toneden-sdk#36]
Is it possible to use the alternative format 'https://api.soundcloud.com/tracks/186624067' inside the urls: property?

**Comment by elsbree** [comment]
This is a very late response, but we just released v2 and it supports this feature. It's not in documentation yet, but instead of a URL, it is possible to provide an object in the form:

```
{
    stream_id: <SoundCloud TrackID>,

}
```
