### ISSUE TITLE
Expose More SoundManager Events

### ISSUE THREAD

**Issue by jackrugile** [ToneDen/toneden-sdk#44]
In addition to the existing `onTrackFinished` and `onTrackReady` events, I'd love to use some of the other SoundManager events, such as `onplay`, `onresume`, `onstop`, and `onpause`.

I'd mainly want to use this feature to control the auto pausing of other tracks on a page when I start playing a new track. This only applies for multiple instances of single track players of course, but that's what I'm using right now.

**Comment by elsbree** [comment]
Sorry for the late response. V2 of the player allows you to listen to events on the ToneDen.player object. You can currently listen to the following events:

'track.error',
'track.played',
'track.paused',
'track.started',
'track.finished'

Listeners to each of these events are called with the track in question as the first argument. This is undocumented, but it will be in the readme soon.
