### ISSUE TITLE
Same-origin-policy // CORS issue with Soundcloud Resolve API? (FF)

### ISSUE THREAD

**Issue by felics** [ToneDen/toneden-sdk#46]
I'm hitting `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://api.soundcloud.com/resolve?url=http://soundcloud.com/giraffage&format=json&consumer_key=xxx. (Reason: CORS header 'Access-Control-Allow-Origin' missing).` on a live site as well as localhost in **Firefox 38**. Any idea what could be wrong? Hitting a brick wall here, your [demo page](https://www.toneden.io/player) seems to work fine.

**Comment by elsbree** [comment]
I did notice that a new version of Chrome was causing trouble, showing CORS errors when we were trying to set up the visualizer. I took out the visualizer from the player and I haven't seen the issue since. Are you using a self-hosted version of the player?
