### ISSUE TITLE
Player Height Bugging

### ISSUE THREAD

**Issue by fschoenfeldt** [ToneDen/toneden-sdk#47]
Hey guys!

I really like your player, though I'm having an issue on our platform with it:

![image](https://cloud.githubusercontent.com/assets/4721311/8115012/d2faaae0-1078-11e5-9fa5-6037ad3d71a7.png)

The player height should be 100% height, the parent div is set to 100%.

```HTML
<div style="width: 40%; float:left; height:100%">
<div id="player"></div>
</div>
```

Once I play a song which has been already played, the player behaves as it's supposed to do.

![image](https://cloud.githubusercontent.com/assets/4721311/8114979/a70a5962-1078-11e5-9925-910c9cc355dd.png)

**Comment by elsbree** [comment]
Do you have a live example of this somewhere? We're going to be reworking our player soon so I hope to add this to the to-do list.
