### ISSUE TITLE
Music doesn't play on Chrome

### ISSUE THREAD

**Issue by peltiphyllum** [ToneDen/toneden-sdk#48]
The music doesn't play on Chrome when I call the toneden-loader.js from my server, but it works correctly when I write the sample code:

script.src = "//sd.toneden.io/production/toneden.loader.js"

The console shows a problem of access restriction.
![capture d ecran 2015-08-04 a 14 32 00](https://cloud.githubusercontent.com/assets/13642297/9060595/9babf564-3ab5-11e5-9d1c-5f757b3216e0.png)

**Comment by elsbree** [comment]
Do you have an example page I could take a look at? You may be using an outdated version of the player on your servers.

**Comment by peltiphyllum** [comment]
Here the development link: http://plaistow.cc/_New-WP/#titan
I use the version who's currently downloadable on GitHub.

**Comment by elsbree** [comment]
Would you mind trying this with the new version of our player? We just released v2, and you shouldn't experience this issue any more with it. The embed snippet has changed slightly, and you'll need to generate a SoundCloud app token to use it.
