### ISSUE TITLE
Track icon (img) stretched to the full width of player. 

### ISSUE THREAD

**Issue by HappyNesti** [ToneDen/toneden-sdk#49]
Track icon (img) stretched to the full width of player. Example attachted. Please help! 
Code is following:

<div id="player"></div>

<script>
    (function() {
        var script = document.createElement("script");

        script.type = "text/javascript";
        script.async = true;
        script.src = "//sd.toneden.io/production/toneden.loader.js"

        var entry = document.getElementsByTagName("script")[0];
        entry.parentNode.insertBefore(script, entry);
    }());

    ToneDenReady = window.ToneDenReady || [];
    ToneDenReady.push(function() {
        // This is where all the action happens:
        ToneDen.player.create({
            dom: "#player",
            eq: "waves",
            skin: "light",
            tracksPerArtist: 4,
            urls: [
                "https://soundcloud.com/mooneylooney/sets/vibes01"
            ],
        single: false,
        mini: false,
       visualizerType: 'bars'
   });
});
</script>

![icon_issue](https://cloud.githubusercontent.com/assets/13794780/9270756/c8a01fae-427c-11e5-9c16-ecd6e611917e.jpg)

**Comment by elsbree** [comment]
Could you provide a link to the site you're seeing this on? We also just released v2 of the player, so that should fix this issue. See the readme for more details- there are a few API changes.
