### ISSUE TITLE
Autoplay

### ISSUE THREAD

**Issue by joeldomingues** [ToneDen/toneden-sdk#50]
Hello, I really dig your plugin, but I have a problem, I can't set the player to autoplay when the page loads. Is it possible?

**Comment by giubil** [comment]
I would guess an easy way to do this would be that after that you did your `ToneDen.player.create(); ` you just call  `ToneDen.player.getInstanceByDom("#your-music-element").togglePause();`

**Comment by elsbree** [comment]
@giubil is right, this is the best way to do autoplaying, since we're probably not going to add an 'autoplay' option to the SDK.
