### ISSUE TITLE
Player crashes when given a link to a playlist

### ISSUE THREAD

**Issue by giubil** [ToneDen/toneden-sdk#52]
Hello, 
I don't know if this is voluntary or not, but when feeding the player an url in the form:

https://soundcloud.com/*/sets/* 

it fails to load.

**Comment by dreamdt** [comment]
Try this patch https://github.com/ToneDen/toneden-sdk/pull/51

**Comment by thathurtabit** [comment]
I have the same issue. Can't get a 'set' to load, but the url should be 'SETS' https://soundcloud.com/nonbeliever/SETS/a-model-of-modern-influence not 'set' or 'playlist'.

Unless the SDK thinks playlists are sets, I'm not sure: https://github.com/dreamdt/toneden-sdk/commit/ea65a634d21625e30f00e191689ceacb2a254818

**Comment by dreamdt** [comment]
@thathurtabit
> the url should be 'SETS'

You are right, 
but this code is not about url, it's about response:
![soundcloud response object](http://i.imgur.com/ICvLAE3.png)

**Comment by thathurtabit** [comment]
@dreamdt Ah. I see. So your solution seems to fix the problem then? Is there a way I can link to your updated version, or do we need to wait until it's merged into https://github.com/ToneDen/toneden-sdk ?
Apologies for my cluelessness.

**Comment by dreamdt** [comment]
1. Yes, it works for me, but you should use "/sets/" inside url (not /SETS/)
2. Inside toneden.loader.js, you should replace "//sd.toneden.io/production/v2/" with your own domain and path. I think it will be enough (if not, it would be better to wait until merge)
https://github.com/dreamdt/toneden-sdk/releases/download/v2.0/toneden-sdk.zip

**Comment by thathurtabit** [comment]
Huzzah @dreamdt! It works! Thank you for your help. Hopefully your fix should get merged soon.

**Comment by elsbree** [comment]
Thanks for fixing this. I just merged the PR by @dreamdt and deployed it to our CDN.
