### ISSUE TITLE
TypeError: ToneDen.configure is not a function

### ISSUE THREAD

**Issue by moongaze** [ToneDen/toneden-sdk#55]
Hello Toneden!

I'm getting an "TypeError: ToneDen.configure is not a function"  exception when I add the code with the consumerkey.
You can check the error here : http://www.kissesfromoblivion.com

It doesnt seem to be mandatory to enter an ID? 
The player works when I remove the ToneDen.configure snippet.
Am I correct in entering the client ID for my soundcloud app? 
What could I be doing wrong?
Also: Should I take steps to mask this ID? If so, how would you recommend doing this?

Thanks !

**Comment by elsbree** [comment]
It looks like you're loading the old version of the script. To use the new player (which has the `configure` method), you'll need to change the script path to `//sd.toneden.io/production/v2/toneden.loader.js`.

There's not much you can do to mask your SoundCloud app ID, unfortunately. Even if you were to find some way to obscure it in your code, it would still be visible in the network calls made to SoundCloud's API.

**Comment by moongaze** [comment]
Thanks for your swift answer!
Cool, the player shows up now!

But, I seem to have found some bugs on my machine using Chrome Version 46.0.2490.80 m, and Firefox 41.0.2. Following css :
 ".td.player .tdicon-td_logo {
     width: 100%;
     height: 100%; }"
seems to makes the toneden link stretch over the controls, so when I press play, it opens the site instead of playing the track.

The mini player does allow access to the controls, but has responsive issues between +-600 and +-1000 px width on forementioned browsers. ![tonedenresposivemini](https://cloud.githubusercontent.com/assets/13341403/10829134/9975573e-7e78-11e5-971a-381d9ecb85c2.jpg)On my phone (1280x720px),strangely enough, it looks as it should in both portrait as landscape mode.

My apologies if you were already aware of those issues or if they are unique to my page.
I'll be using the mini player for now!
