### ISSUE TITLE
Bower package? Is it possible?

### ISSUE THREAD

**Issue by ZhiguoZhang** [ToneDen/toneden-sdk#59]
Hi, I am a new bee of angular, I'm building a page with angular and it would be great, if you could make the ToneDen in to Bower as a components, then I could easier integrate ToneDen into my project. Do you think it is possible? Thank you!

**Comment by elsbree** [comment]
I don't personally have any experience with Bower, so I don't think I'll be able to help with this. If anyone wants to submit a PR, I'd be happy to look it over.

**Comment by ZhiguoZhang** [comment]
I can try to do a PR, but at the end, you have to go to http://bower.io/docs/creating-packages/ register the package. I don't know do you want to do that or not?

**Comment by elsbree** [comment]
I only have experience with NPM, so if I was going to create a package from this repo that's probably what I would want to use. That being said, I don't think I have time for the additional work of keeping this repository in a package management system.
