### ISSUE TITLE
Production version has issues with audio stats.

### ISSUE THREAD

**Issue by XIIIzen** [ToneDen/toneden-sdk#61]
I used the audio player production version and it can't in any way pull the stats for the audio file I'm using.

However, if I use the dev version of the player, it works properly. I believe there is something happening in the production side of things that breaks the stats.

Oh also, the dev version fixes the error on this issue: 403 Forbidden Error when intergrate v2 Toneden.loader.js!

**Comment by elsbree** [comment]
I just fixed the 403 Forbidden error in the production version of the player, see issue #60.

As for the audio stats, I'm not sure what you mean- are you having trouble accessing the length/size of the stream? And is this a SoundCloud track you're playing, or a direct link to an audio file?
