### ISSUE TITLE
Can't get togglePause() to work at all?

### ISSUE THREAD

**Issue by HandHugs** [ToneDen/toneden-sdk#71]
I am not sure what I am doing wrong. Can anyone help?

I just get the error:

Uncaught TypeError: ToneDen.player.getInstanceByDom(...).togglePause is not a function

http://codepen.io/handhugs/pen/dXWqgk

**Comment by elsbree** [comment]
Sorry for not responding sooner. It looks like you're loading the old version of the player, where the `togglePause` function doesn't exist. You'll need to change your URL to `//sd.toneden.io/production/v2/toneden.loader.js`.
