### ISSUE TITLE
Wordpress shortcode not updated?

### ISSUE THREAD

**Issue by sauranus** [ToneDen/toneden-sdk#72]
Hi,

I'm using the wordpress shortcode but it seems the stand alone player has been updated while the wordpress shortcode is still based on the old version. 

The old version prevents some pages of my website to load. And I think this could be fixed by using the new version. You can see on the screenshot some ressources are not loading (menu, images, products), while it works perfectly when the player is deactivated:
![screeshot-atelier](https://cloud.githubusercontent.com/assets/20395893/16725960/1a6c4e56-475a-11e6-8bad-6f234888b0a9.PNG)

Thanks for your help!

**Comment by elsbree** [comment]
Have you tried embedding the new version of the player using Javascript? We haven't updated the shortcode in a while, but you should be able to use the new version of the player if you just use a script tag like in the Readme.
