### ISSUE TITLE
Origin is not allowed by Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by ctf0** [ToneDen/toneden-sdk#73]
using the link like

``` js
"//sd.toneden.io/production/v2/toneden.loader.js"
```

gives the origin error but removeing the version like

``` js
"//sd.toneden.io/production/toneden.loader.js"
```

seems to fix the issue.

**Comment by bataninkovic** [comment]
still not working

**Comment by elsbree** [comment]
Can you send me an example of a page where you see this error?

**Comment by ctf0** [comment]
@elsbree its on localhost
