### ISSUE TITLE
Song played size

### ISSUE THREAD

**Issue by RasmusFriis** [ToneDen/toneden-sdk#76]
On my website http://voxsagitarius.com/, I have used the wordpress plugin recently. But I cant understand why the class "track-info-plays" do not show the same number than in Soundcloud, 

for example, the first song in the list "Sri Mohangar" should show around 3773, and not 1716, as in the imbeded player. 

Can someone meaby fix this issue. 

![screenshot 2016-08-03 22 52 25](https://cloud.githubusercontent.com/assets/2698355/17381599/0623f34c-59cd-11e6-8d62-1884c9661a9a.png)
![screenshot 2016-08-03 22 52 06](https://cloud.githubusercontent.com/assets/2698355/17381623/250c2eaa-59cd-11e6-9436-70d8ce32b335.png)

**Comment by elsbree** [comment]
I've looked into this, and the only explanation I can find is that SoundCloud's API is returning the incorrect value (it wouldn't be the first time). When I get the track from SoundCloud using the command `curl 'https://api.soundcloud.com/tracks/217831825.json?consumer_key=3c5c65d3883f44774065c7741f5220f8' --compressed | python -mjson.tool`, I see the `playback_count` value set to 1,727. Unfortunately there's nothing I can do from my end to fix that.
