### ISSUE TITLE
Size issue in mobile browser

### ISSUE THREAD

**Issue by scottleee** [ToneDen/toneden-sdk#77]
I'm having a problem where my the player sizes differently in the desktop and mobile versions of my website (http://scottleemusic.net). I've made the overflow hidden on the mobile version for now, so it doesn't overlap onto the content below it, but it's a bandaid solution. The problem seems to be that the repeat song and volume buttons appear on either side of the track name on the desktop browser, while on the mobile browser they appear on the top and bottom, taking up more space. Any help you could offer would be greatly appreciated!

**Comment by elsbree** [comment]
If you'd like to change the way the player renders on a mobile browser, you'll have to fork it. We're not currently updating the looks of the player, but we will be fixing bugs if they get reported.
