### ISSUE TITLE
Elements dissapear below ca. 1024 px width

### ISSUE THREAD

**Issue by 70hundert** [ToneDen/toneden-sdk#79]
Hi there!

I like you script and i'm using it on a responsive site with full width and positioned at the bottom.

However, when I resize the window width below ca. 1024px, the "mini-scrubber", "mini-info", "mini-social" and "mini-connect" elements are disappearing.

I tried to edit the foundation.min.css-file, but no luck with that.

How can I display the mentioned elements to a width of 600 px?

**Comment by elsbree** [comment]
This is meant to make the player more responsive. You can see the relevant line of code [here](https://github.com/ToneDen/toneden-sdk/blob/0e0c5aa634d82dcf8e9afdc8ee77219299831980/sdk/css/player.css#L1701). Those rules are only applied at smaller screen sizes.
